modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"

[[mods]]
modId="livingfrontier"
version="${version}"
displayName="Living Frontier"
authors="GHogbin"
description='''Wildlife, roaming raiders, guarded camps and a ruined-keep boss. First Forge beta.'''

[[dependencies.livingfrontier]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"

[[dependencies.livingfrontier]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
