modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"

[[mods]]
modId="livingfrontier"
version="${version}"
displayName="Living Frontier"
authors="GHogbin"
description='''A lived-in world with wilderness trade roads, roadside settlements, cargo merchants, biome-themed villages, wildlife and puzzle-maze fortresses.'''

[[dependencies.livingfrontier]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"

[[dependencies.livingfrontier]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
