modLoader="javafml"
loaderVersion="[47,48)"
license="MIT"

[[mods]]
modId="livingfrontier"
version="${version}"
displayName="Living Frontier"
authors="GHogbin"
description='''Wildlife, prowler packs, flying wraiths, guarded bases and occasional hostile wilderness encounters.'''

[[dependencies.livingfrontier]]
modId="forge"
mandatory=true
versionRange="[47.4.0,48)"
ordering="NONE"
side="BOTH"

[[dependencies.livingfrontier]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="BOTH"
